language: csharp
solution: Starry.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore ./src/Starry.sln

script:
  - xbuild ./src/Starry.sln
  - nunit-console ./src/Starry.Test/bin/Debug/Starry.Test.dll
